# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\akhiat mohamed\GitHub\ElectroMotorCalc-Datasheet-Manager\ui_windows\Graphs_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{background-image: url(:/bcg_image/Images for Program/png_worldwide.png);}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.Drehzahl_label = QtWidgets.QLabel(self.centralwidget)
        self.Drehzahl_label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Drehzahl_label.setFont(font)
        self.Drehzahl_label.setStyleSheet("color:rgb(255, 255, 255)")
        self.Drehzahl_label.setObjectName("Drehzahl_label")
        self.gridLayout.addWidget(self.Drehzahl_label, 1, 0, 1, 1)
        self.DrehzahlLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.DrehzahlLineEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.DrehzahlLineEdit.setFont(font)
        self.DrehzahlLineEdit.setStyleSheet("border-radius:2px")
        self.DrehzahlLineEdit.setObjectName("DrehzahlLineEdit")
        self.gridLayout.addWidget(self.DrehzahlLineEdit, 1, 1, 1, 1)
        self.Drehmoment_label = QtWidgets.QLabel(self.centralwidget)
        self.Drehmoment_label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.Drehmoment_label.setFont(font)
        self.Drehmoment_label.setStyleSheet("color:rgb(255, 255, 255)")
        self.Drehmoment_label.setObjectName("Drehmoment_label")
        self.gridLayout.addWidget(self.Drehmoment_label, 2, 0, 1, 1)
        self.DrehmomentLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.DrehmomentLineEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.DrehmomentLineEdit.setFont(font)
        self.DrehmomentLineEdit.setStyleSheet("border-radius:2px")
        self.DrehmomentLineEdit.setObjectName("DrehmomentLineEdit")
        self.gridLayout.addWidget(self.DrehmomentLineEdit, 2, 1, 1, 1)
        self.tabwidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabwidget.setStyleSheet("border-radius:2px")
        self.tabwidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabwidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabwidget.setObjectName("tabwidget")
        self.gridLayout.addWidget(self.tabwidget, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabwidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Drehzahl_label.setText(_translate("MainWindow", "Drehzahl [1/min]"))
        self.Drehmoment_label.setText(_translate("MainWindow", "Drehmoment [Nm]"))
import bcg_image_rc
